services:
  - name: web
    env:
      - key: FLASK_APP
        value: app:app  # Reemplaza 'yourapp' con el nombre de tu archivo de aplicación Flask
      - key: FLASK_ENV
        value: production
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app  # Reemplaza 'yourapp' con el nombre de tu archivo de aplicación Flask
